model:
  # number of input channels to the model
  in_channels: 5
  # number of output channels
  out_channels: 3
  # Conv3D kernel sizes
  kernels: [[3, 3, 3], [3, 3, 3], [3, 3, 3], [3, 3, 3], [3, 3, 3], [3, 3, 3], [3, 3, 3]]
  # Conv3D strides
  strides:  [[1, 1, 1], [2, 2, 2], [2, 2, 2], [2, 2, 2], [2, 2, 2], [2, 2, 2], [2, 2, 2]]
  # Conv3D filter sizes
  filters: [64, 96, 128, 192, 256, 384, 512]
  # use deep supervision
  deep_supervision: true

loss:
  include_background: false
  simgoid: true
  batch: true
  gamma: 2.0

optimizer:
  # initial learning rate
  learning_rate: 0.0002
  # weight decay
  weight_decay: 0.00001

lr_scheduler:
  name: ReduceLROnPlateau
  # make sure to use the 'min' mode cause lower AdaptedRandError is better
  mode: min
  factor: 0.5
  patience: 30